#############################################################################
# Makefile for building: zombiebli
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sat May 25 18:53:46 2013
# Project:  zombiebli.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile zombiebli.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-blieng \
		sub-src

blieng//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) blieng/ || $(MKDIR) blieng/ 
	cd blieng/ && $(QMAKE) /home/roivas/projects/zombiebli/blieng/blieng.pro -o $(MAKEFILE)
sub-blieng-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) blieng/ || $(MKDIR) blieng/ 
	cd blieng/ && $(QMAKE) /home/roivas/projects/zombiebli/blieng/blieng.pro -o $(MAKEFILE)
sub-blieng: blieng//$(MAKEFILE) FORCE
	cd blieng/ && $(MAKE) -f $(MAKEFILE)
sub-blieng-make_default: blieng//$(MAKEFILE) FORCE
	cd blieng/ && $(MAKE) -f $(MAKEFILE) 
sub-blieng-make_first: blieng//$(MAKEFILE) FORCE
	cd blieng/ && $(MAKE) -f $(MAKEFILE) first
sub-blieng-all: blieng//$(MAKEFILE) FORCE
	cd blieng/ && $(MAKE) -f $(MAKEFILE) all
sub-blieng-clean: blieng//$(MAKEFILE) FORCE
	cd blieng/ && $(MAKE) -f $(MAKEFILE) clean
sub-blieng-distclean: blieng//$(MAKEFILE) FORCE
	cd blieng/ && $(MAKE) -f $(MAKEFILE) distclean
sub-blieng-install_subtargets: blieng//$(MAKEFILE) FORCE
	cd blieng/ && $(MAKE) -f $(MAKEFILE) install
sub-blieng-uninstall_subtargets: blieng//$(MAKEFILE) FORCE
	cd blieng/ && $(MAKE) -f $(MAKEFILE) uninstall
src//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/roivas/projects/zombiebli/src/src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/roivas/projects/zombiebli/src/src.pro -o $(MAKEFILE)
sub-src: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: zombiebli.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile zombiebli.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile zombiebli.pro

qmake_all: sub-blieng-qmake_all sub-src-qmake_all FORCE

make_default: sub-blieng-make_default sub-src-make_default FORCE
make_first: sub-blieng-make_first sub-src-make_first FORCE
all: sub-blieng-all sub-src-all FORCE
clean: sub-blieng-clean sub-src-clean FORCE
distclean: sub-blieng-distclean sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-blieng-install_subtargets sub-src-install_subtargets FORCE
uninstall_subtargets: sub-blieng-uninstall_subtargets sub-src-uninstall_subtargets FORCE

sub-blieng-check: blieng/$(MAKEFILE)
	cd blieng/ && $(MAKE) -f $(MAKEFILE) check
sub-src-check: src/$(MAKEFILE)
	cd src/ && $(MAKE) -f $(MAKEFILE) check
check: sub-blieng-check sub-src-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

